### ISSUE TITLE
check response code from urllib.urlopen in fetch_from_url

### ISSUE THREAD

**Issue by rickmcgeer** [EdgeNet-project/portal#2]
The current assumption is that a bad fetch will cause an exception, but that isn't necessarily true.

**Comment by aaaaalbert** [comment]
See also EdgeNet-Project/headnode#30. Assumptions do not work well. Standardized status codes and exceptions do.

**Comment by aaaaalbert** [comment]
This is implemented in https://github.com/EdgeNet-project/portal/commit/15646a5ea3925a1bbfef255a3df6c5522bbfac00#diff-d7435cb254e4214f7df64fd95b3e1224R273 (and following lines). Closing this issue.
